# frozen_string_literal: true

require_relative 'technologies/version'

module MapleTech
  class Technologies
    class Error < StandardError; end

    # rubocop:disable Metrics/CollectionLiteralLength
    def self.all
      [
        'Not Applicable',
        '.QL',
        '@Formula',
        '4D (4th Dimension)',
        'A-0 System',
        'A.NET',
        'A/ROSE',
        'A/UX (UNIX System V with BSD extensions)',
        'A+',
        'ABAP',
        'ABC',
        'ABC ALGOL',
        'ACC',
        'Accent',
        'Ace DASL (Distributed Application Specification Language)',
        'Action!',
        'ActionScript',
        'Actor',
        'Ada',
        'ADABAS',
        'Adenine',
        'Adobe PhoneGap',
        'AdvPL',
        'Agda',
        'Agilent VEE',
        'Agora',
        'AIMMS',
        'Aldor',
        'Alef',
        'ALF',
        'ALGOL 58',
        'ALGOL 60',
        'ALGOL 68',
        'ALGOL W',
        'Alice',
        'Alma-0',
        'Altibase',
        'Amazon ECS',
        'AmazonRDS',
        'AmbientTalk',
        'Amiga E',
        'AMOS',
        'AMPL',
        'Android',
        'AngelScript',
        'Apache Pig latin',
        'Apache Wicket',
        'Apex',
        'APL',
        "App Inventor for Android's visual block language",
        'Apple DOS',
        'Apple II family',
        'Apple III',
        'Apple Lisa',
        'Apple Macintosh',
        'Apple MessagePad',
        'Apple Network Server',
        'Apple Pascal',
        'Apple SOS',
        'Apple TV',
        'Apple Watch',
        'AppleScript',
        'APT',
        'Aqua Security',
        'Arc',
        'Arch Linux',
        'ARexx',
        'Argus',
        'ASP.NET',
        'ASP.NET Core',
        'ASP.NET MVC',
        'Assembly language',
        'AutoHotkey',
        'AutoIt',
        'AutoLISP / Visual LISP',
        'Averest',
        'AWK',
        'Axum',
        'Azure Container Service (AKS)',
        'Azure Sphere',
        'B',
        'Babbage',
        'Ballerina',
        'Bash',
        'BASIC',
        'Batch file (Windows/MS-DOS)',
        'bc',
        'BCPL',
        'BeanShell',
        'Bertrand',
        'BETA',
        'BLISS',
        'Blockbridge',
        'Blockly',
        'BlooP',
        'Boo',
        'Boomerang',
        'Bootstrap',
        'Bottle',
        'Buddy',
        'C – ISO/IEC 9899',
        'C Shell (csh)',
        'C-- (C minus minus)',
        'C*',
        'C/AL',
        'C# (C sharp) – ISO/IEC 23270',
        'C++ (C plus plus) – ISO/IEC 14882',
        'Caché ObjectScript',
        'cAdvisor',
        'CakePHP',
        'Caml',
        'Catalyst',
        'Cayenne',
        'CDuce',
        'Cecil',
        'CEEMAC',
        'CentOS',
        'Cesil',
        'Céu',
        'Ceylon',
        'CFEngine',
        'Cg',
        'Ch',
        'Chapel',
        'Charm',
        'CherryPy',
        'CHILL',
        'CHIP-8',
        'chomski',
        'ChucK',
        'Cilk',
        'CirclCI',
        'CL (IBM)',
        'Clair',
        'Claire',
        'Clarion',
        'Classic Mac OS',
        'Clean',
        'Clipper',
        'CLIPS',
        'CLIST',
        'Clojure',
        "Cloud Foundary's Diego",
        'Cloud Foundry',
        'Cloudera',
        'CLU',
        'CMS EXEC (EXEC)',
        'CMS-2',
        'COBOL – ISO/IEC 1989',
        'CobolScript – COBOL Scripting language',
        'Cobra',
        'CodeFresh',
        'Codeigniter',
        'CodeShip',
        'CoffeeScript',
        'ColdFusion',
        'COMAL',
        'Combined Programming Language (CPL)',
        'COMIT',
        'Common Intermediate Language (CIL)',
        'Common Lisp (also known as CL)',
        'COMPASS',
        'Component Pascal',
        'COMTRAN',
        'Constraint Handling Rules (CHR)',
        'Consul',
        'containerd',
        'Contiki',
        'Convoy',
        'Cool',
        'Copland',
        'Coq',
        'Coral 66',
        'Corona',
        'CorVision',
        'Couchbase',
        'CouchDB',
        'COWSEL',
        'CPL',
        'Cryptol',
        'Crystal',
        'Csound',
        'CSS',
        'Cuneiform',
        'Curl',
        'Curry',
        'Cybil',
        'Cyclone',
        'Cypher Query Language',
        'Cython',
        'D',
        'Dart',
        'Darwin',
        'Datadog',
        'DataFlex',
        'Datalog',
        'DATATRIEVE',
        'DAX (Data Analysis Expressions)',
        'dBase',
        'DbVisualizer',
        'dc',
        'DCL',
        'Debian',
        'Delphi',
        'DIBOL',
        'DinkC',
        'Django',
        'Docker',
        'Docker Bench for Security',
        'Docker Notary',
        'Docker Swarm',
        'Dog',
        'DOS/V',
        'Draco',
        'DRAKON',
        'Drone',
        'Drupal',
        'Dylan',
        'DYNAMO',
        'E',
        'Ease',
        'Easy PL/I',
        'EASYTRIEVE PLUS',
        'eC',
        'ECMAScript',
        'Edinburgh IMP',
        'EGL',
        'Eiffel',
        'ELAN',
        'Elm',
        'Emacs Lisp',
        'Embedded operating systems',
        'Emerald',
        'Epigram',
        'EPL (Easy Programming Language)',
        'EPL (Eltron Programming Language)',
        'Erlang',
        'es',
        'Escher',
        'ESPOL',
        'Esterel',
        'Etcd',
        'Etoys',
        'Euclid',
        'Euler',
        'Euphoria',
        'EusLisp Robot Programming Language',
        'EXEC 2',
        'Executable UML',
        'Express.js',
        'Ezhil',
        'F',
        'F-Script',
        'F*',
        'F#',
        'Factor',
        'Fantom',
        'FastAPI',
        'Fat-Free',
        'FAUST',
        'Fedora',
        'FFP',
        'FileMaker',
        'fish',
        'Fjölnir',
        'FL',
        'flannel',
        'Flask',
        'Flavors',
        'Flex',
        'FlooP',
        'FLOW-MATIC',
        'Fluentd',
        'Flutter',
        'FOCAL',
        'FOCUS',
        'FOIL',
        'FORMAC',
        'Forth',
        'Fortran – ISO/IEC 1539',
        'Fortress',
        'FP',
        'Franz Lisp',
        'FreeBasic',
        'FuelPHP',
        'Futhark',
        'G-code',
        'Game Maker Language (Scripting language)',
        'GameMonkey Script',
        'GAMS',
        'GAP',
        'Gatsby',
        'GDL',
        'GDScript',
        'Genie',
        'Gentoo Linux',
        'GEORGE',
        'Github',
        'Gitlab',
        'Gitlab CI',
        'GLSL',
        'GNO/ME',
        'GNU E',
        'GNU Guile',
        'Go',
        'Go!',
        'GOAL',
        'Gödel',
        'Golo',
        'GOM (Good Old Mad)',
        'Google Apps Script',
        'Google Container Engine (GKE)',
        'Gosu',
        'GOTRAN',
        'GPSS',
        'Gradle',
        'Grails',
        'GraphTalk',
        'GraphQL',
        'GRASS',
        'Grasshopper',
        'Grok',
        'Groovy',
        'GS/OS',
        'Hack',
        'Hadoop HDFS',
        'HAGGIS',
        'HAL/S',
        'Halide (programming language)',
        'Hamilton C shell',
        'Harbour',
        'Hartmann pipelines',
        'HashiCorp Nomand',
        'Haskell',
        'Haxe',
        'Helios',
        'Hermes',
        'High Level Assembly',
        'HLSL',
        'Hollywood',
        'HolyC',
        'Hop',
        'Hope',
        'Hopscotch',
        'HTML',
        'Hugo',
        'Hume',
        'HyperTalk',
        'IBM AIX (Apple-customized)',
        'IBM Basic assembly language',
        'IBM DB2',
        'IBM HAScript',
        'IBM Informix-4GL',
        'IBM RPG',
        'Icon',
        'IDL',
        'Idris',
        'Inform',
        'Informix',
        'Informix Dynamic Server',
        'Io',
        'Ionic',
        'iOS (formerly iPhone OS)',
        'iPad',
        'iPadOS',
        'iPhone and iPod Touch',
        'iPod software (unnamed embedded OS for iPod)',
        'J',
        'J#',
        'J++',
        'JADE',
        'JAL',
        'Janus (concurrent constraint programming language)',
        'Janus (time-reversible computing programming language)',
        'JASS',
        'JavaFX Script',
        'JavaScript(Scripting language)',
        'JCL',
        'JEAN',
        'Jenkins',
        'Jess (programming language)',
        'JHipster',
        'Join Java',
        'JOSS',
        'Joule',
        'JOVIAL',
        'Joy',
        'jQuery',
        'JQuery Mobile',
        'JScript',
        'JScript .NET',
        'Julia',
        'Jython',
        'K',
        'Kaleidoscope',
        'Kali',
        'Karel',
        'KEE',
        'KIF',
        'Kixtart',
        'Klerer-May System',
        'KNOPPIX',
        'Kodu',
        'Kohana',
        'Kojo',
        'KornShell (ksh)',
        'Kotlin',
        'KRC',
        'KRL',
        'KRL (KUKA Robot Language)',
        'KRYPTON',
        'Kubernetes',
        'Kv',
        'LabVIEW',
        'Ladder',
        'Language H',
        'LANSA',
        'Laravel',
        'Lasso',
        'Lava',
        'LC-3',
        'Lean',
        'Legoscript',
        'Lift',
        'LIL',
        'LilyPond',
        'Limbo',
        'Limnor',
        'LINC',
        'Lingo',
        'LINQ',
        'Linux Mint',
        'LIS',
        'LISA',
        'Lisp – ISO/IEC 13816',
        'Lite-C',
        'Lithe',
        'Little b',
        'LiveCode',
        'LiveScript',
        'LLL',
        'Logo',
        'Logspout',
        'Logstash',
        'Logtalk',
        'LotusScript',
        'LPC',
        'LSE',
        'LSL',
        'Lua',
        'Lucid',
        'Lumen',
        'Lustre',
        'LXC',
        'LYaPAS',
        'Lynx',
        'M#',
        'M2001',
        'M4',
        'Machine code',
        'macOS (formerly Mac OS X and OS X)',
        'macOS Server (formerly Mac OS X Server and OS X Server)',
        'MAD (Michigan Algorithm Decoder)',
        'MAD/I',
        'Mageia',
        'Magik',
        'Magma',
        'Máni',
        'Maple',
        'MAPPER (now part of BIS)',
        'Marathon',
        'MariaDB',
        'MARK-IV (now VISION:BUILDER)',
        'Mary',
        'MASM Microsoft Assembly x86',
        'Mason',
        'MATH-MATIC',
        'MATLAB',
        'Maude system',
        'Max (Max Msp – Graphical Programming Environment)',
        'Maxima (see also Macsyma)',
        'MaxScript internal language 3D Studio Max',
        'Maya (MEL)',
        'MDL',
        'Merb',
        'Mercury',
        'Mesa',
        'Mesosphere DC/OS',
        'MHEG-5 (Interactive TV programming language)',
        'Microcode',
        'MicroScript',
        'Microsoft Access',
        'Microsoft SQL Server',
        'Midori – A managed code operating system',
        'MIIS',
        'Milk (programming language)',
        'MIMIC',
        'Mirah',
        'Miranda',
        'MIVA Script',
        'MkLinux',
        'ML',
        'Mobile Angular UI',
        'Model 204',
        'Modelica',
        'Modula',
        'Modula-2',
        'Modula-3',
        'Mohol',
        'Mojolicious',
        'MongoDB',
        'MOO',
        'MooTools',
        'Mortran',
        'Mouse',
        'MPD',
        'MS-DOS (developed jointly with IBM',
        'MSL',
        'MSX-DOS (developed by MS Japan for the MSX 8-bit computer)',
        'MUMPS',
        'MuPAD',
        'Mutan',
        'MySQL',
        'Mystic Programming Language (MPL)',
        'Napier88',
        'NASM',
        'Native scripts',
        'Nebula',
        'Neko',
        'Nemerle',
        'Neo4j',
        'NESL',
        'Net.Data',
        'NetLogo',
        'NetRexx',
        'New Relic',
        'NewLISP',
        'NEWP',
        'Newspeak',
        'Newton OS',
        'NewtonScript',
        'Next.js',
        'Nial',
        'Nickle (NITIN)',
        'Nim',
        'Nix (Systems configuration language)',
        'Not eXactly C (NXC)',
        'Not Quite C (NQC)',
        'NPL',
        'NSIS',
        'Nu',
        'NWScript',
        'NXT-G',
        'o:XML',
        'Oak',
        'Oberon',
        'OBJ2',
        'Object Lisp',
        'Object Pascal',
        'Object REXX',
        'Objective-C',
        'Objective-J',
        'ObjectLOGO',
        'Obliq',
        'OCaml',
        'occam',
        'occam-π',
        'Octave',
        'OmniMark',
        'Opa',
        'Opal',
        'OpenCL',
        'OpenEdge ABL',
        'openSUSE',
        'OpenVera',
        'OPL',
        'OPS5',
        'OptimJ',
        'Oracle Linux',
        'Oracle RDBMS',
        'Orc',
        'ORCA/Modula-2',
        'Oriel',
        'OrientDB',
        'Orwell',
        'OS/2 1.x (developed jointly with IBM until version 1.3)',
        'Other',
        'Oxygene',
        'Oz',
        'P',
        'P′′',
        'P4',
        'Packer',
        'Padrino',
        'ParaSail (programming language)',
        'PARI/GP',
        'Pascal – ISO 7185',
        'Pascal Script',
        'PCASTL',
        'PCF',
        'PDL',
        'PEARL',
        'PeopleCode',
        'Perl',
        'Phalcon',
        'Pharo',
        'PHP',
        'phpMyAdmin',
        'Pico',
        'Picolisp',
        'Pict',
        'Pike',
        'PILOT',
        'Pink',
        'Pipelines',
        'Pizza',
        'PL-11',
        'PL/0',
        'PL/B',
        'PL/C',
        'PL/I – ISO 6160',
        'PL/M',
        'PL/P',
        'PL/SQL',
        'PL360',
        'PLANC',
        'Plankalkül',
        'Planner',
        'Play',
        'PLEX',
        'PLEXIL',
        'Plus',
        'POP-11',
        'POP-2',
        'PortablE',
        'Portainer',
        'Portworx',
        'PostgresSQL',
        'PostScript',
        'POV-Ray SDL',
        'PowerBuilder – 4GL GUI application generator from Sybase',
        'Powerhouse',
        'PowerShell',
        'PPL',
        'PRADO',
        'Pro*C',
        'Processing',
        'Processing.js',
        'ProDOS',
        'Prograph',
        'PROIV',
        'Project Calico',
        'Project Verona',
        'Prolog',
        'PROMAL',
        'Promela',
        'Prometheus',
        'PROSE modeling language',
        'PROTEL',
        'ProvideX',
        'Proxy',
        'Pure',
        'Pure Data',
        'PureScript',
        'Pylons',
        'Q (programming language from Kx Systems)',
        'Q# (Microsoft programming language)',
        'Qalb',
        'QPL',
        'QtScript',
        'QuakeC',
        'Quantum Computation Language',
        'Quixote',
        'R',
        'R++',
        'Racket',
        'Rails',
        'Raku',
        'Rancher',
        'RAPID',
        'Rapira',
        'Ratfiv',
        'Ratfor',
        'rc',
        'React',
        'React native',
        'Reason',
        'REBOL',
        'Red',
        'Red Hat Enterprise Linux',
        'Red Hat OpenShift',
        'Redcode',
        'Redis',
        'REFAL',
        'REXX',
        'Rhapsody',
        'rkt',
        'Rlab',
        'Robomongo',
        'ROOP',
        'RPG',
        'RPL',
        'RSL',
        'RTL/2',
        'Ruby',
        'Rust',
        'S',
        'S-Lang',
        'S-PLUS',
        'S/SL',
        'S2',
        'S3',
        'SA-C',
        'SabreTalk',
        'SAIL',
        'SAP Sybase ASE',
        'SAS',
        'SASL',
        'Sather',
        'Sawzall',
        'SBL',
        'Scala',
        'Scalatra',
        'Scheme',
        'Scientific Linux',
        'Scilab',
        'Scratch',
        'Script.NET',
        'SCSS',
        'Seaside',
        'Sed',
        'Seed7',
        'Self',
        'Sencha Ext JS',
        'SenseTalk',
        'Seqel PRO',
        'SequenceL',
        'Serpent',
        'SETL',
        'Shippable',
        'SIGNAL',
        'SiMPLE',
        'SIMPOL',
        'SIMSCRIPT',
        'Simula',
        'Simulink',
        'Sinatra',
        'Singularity',
        'Singularity – A research operating system written mostly in managed code (C#)',
        'SISAL',
        'Slackware Linux',
        'SLIP',
        'SMALL',
        'Smalltalk',
        'SML',
        'Snap!',
        'SNOBOL (SPITBOL)',
        'Snowball',
        'SOL',
        'SolarWinds Database Performance Analyzer',
        'Solidity',
        'SOPHAEROS',
        'Source',
        'SP/k',
        'SPARK',
        'Speakeasy',
        'Speedcode',
        'SPIN',
        'SPS',
        'SQL',
        'SQL Developer',
        'SQLite',
        'SQR',
        'Squeak',
        'Squirrel',
        'SR',
        'Starlogo',
        'Stata',
        'Stateflow',
        'Strand',
        'Strongtalk',
        'Subtext',
        'Sumo Logic',
        'SuperCollider',
        'SuperTalk',
        'SUSE Linux',
        'Svelte',
        'Swift (Apple programming language)',
        'Swift (parallel scripting language)',
        'Swiftic',
        'Symfony',
        'SYMPL',
        'Sysdig Monitor',
        'syslog-ng',
        'SystemVerilog',
        'T',
        'T-SQL',
        'TACL',
        'TACPOL',
        'TADS',
        'TAL',
        'Tcl',
        'Tea',
        'TECO',
        'TELCOMP',
        'Teradata',
        'TeX',
        'ThreadX',
        'TIE',
        'TMG',
        'Toad',
        'Toi',
        'Tom',
        'Topspeed',
        'TPU',
        'Trac',
        'Transcript',
        'Travis CI',
        'TTCN',
        'TTM',
        'TurboGears',
        'Turing',
        'TUTOR',
        'tvOS',
        'Twistlock',
        'TXL',
        'Tynker',
        'TypeScript',
        'Ubercode',
        'Ububtu',
        'UCSD Pascal',
        'Umple',
        'Underscore',
        'Unicon',
        'Uniface',
        'UNITY',
        'Unix shell',
        'Unix System III',
        'Unix System IV',
        'Unix System V',
        'Unix System V Releases 2.0',
        'UNIX Time-Sharing System v1',
        'UNIX Time-Sharing System v10',
        'UNIX Time-Sharing System v2',
        'UNIX Time-Sharing System v3',
        'UNIX Time-Sharing System v4',
        'UNIX Time-Sharing System v5',
        'UNIX Time-Sharing System v6',
        'UNIX Time-Sharing System v8',
        'UNIX TIme-Sharing System v9',
        'Unnamed NetBSD variant for Airport Extreme and Time Capsule',
        'UnrealScript',
        'Vaadin',
        'Vagrant',
        'Vala',
        'Verilog',
        'VHDL',
        'Vim script',
        'Viper',
        'VirtualBox',
        'Visual DataFlex',
        'Visual DialogScript',
        'Visual FoxPro',
        'Visual J++',
        'Visual LISP',
        'Visual Objects',
        'Visual Prolog',
        'Vue.js',
        'watchOS',
        'WATFIV',
        'Weaveworks',
        'web2py',
        'WebAssembly',
        'WebDNA',
        'Whales',
        'Whiley',
        'Winbatch',
        'Windows (16-bit and 32-bit preemptive and cooperative multitasking',
        'Windows 1.0 (Windows 1)',
        'Windows 10 (Windows NT 10)',
        'Windows 10 Mobile',
        'Windows 2.0 (Windows 2 – separate version for i386 processor)',
        'Windows 2000 (Windows NT 5.0)',
        'Windows 3.0 (Windows 3)',
        'Windows 3.1x (Windows 3.1)',
        'Windows 3.2 (Chinese-only release)',
        'Windows 7 (Windows NT 6.1)',
        'Windows 8 (Windows NT 6.2)',
        'Windows 8.1 (Windows NT 6.3)',
        'Windows 95 (codename Chicago – Windows 4.0)',
        'Windows 98 (codename Memphis – Windows 4.1)',
        'Windows Azure (Cloud OS Platform) 2009',
        'Windows CE (OS for handhelds',
        'Windows CE 3.0',
        'Windows CE 5.0',
        'Windows CE 6.0',
        'Windows Embedded Compact 2013',
        'Windows Embedded Compact 7',
        'Windows for Workgroups 3.1 (Codename Snowball)',
        'Windows for Workgroups 3.11',
        'Windows Fundamentals for Legacy PCs (based on Windows XP)',
        'Windows Home Server (based on Windows Server 2003)',
        'Windows Home Server 2011 (based on Windows Server 2008 R2)',
        'Windows Millennium Edition (Windows ME – Windows 4.9)',
        'Windows Mobile (based on Windows CE',
        'Windows NT (Full 32-bit or 64-bit kernel',
        'Windows NT 3.1',
        'Windows NT 3.5',
        'Windows NT 3.51',
        'Windows NT 4.0',
        'Windows Phone 7',
        'Windows Phone 8',
        'Windows Phone 8.1',
        'Windows Server 2003 (Windows NT 5.2)',
        'Windows Server 2008 (based on Windows Vista)',
        'Windows Server 2008 R2 (based on Windows 7)',
        'Windows Server 2012 (based on Windows 8)',
        'Windows Server 2012 R2 (based on Windows 8.1)',
        'Windows Server 2016',
        'Windows Server 2019',
        'Windows Vista (Windows NT 6.0)',
        'Windows XP (Windows NT 5.1)',
        'Wolfram Language',
        'Wordpress',
        'Wrecker',
        'Wt',
        'Wyvern',
        'X++',
        'X10',
        'Xamarin',
        'xBase',
        'xBase++',
        'XBL',
        'Xbox 360 system software',
        'Xbox One system software',
        'XC (targets XMOS architecture)',
        'Xenix (licensed version of Unix; licensed to SCO in 1987)',
        'xHarbour',
        'XHTML',
        'XL',
        'Xod',
        'Xojo',
        'XOTcl',
        'XPL',
        'XPL0',
        'XQuery',
        'XSB',
        'XSharp',
        'XSLT',
        'Xtend',
        'YAML',
        'Yesod',
        'Yii',
        'Yoix',
        'Yorick',
        'YQL',
        'YUI',
        'Z notation',
        'Z++',
        'Zebra',
        'Zend',
        'Zeno',
        'ZetaLisp',
        'Zig',
        'ZOPL',
        'ZPL',
        # Suggestions Round 1
        'Ember.JS',
        'Grafana',
        'Google Firebase',
        'ROS',
        'influxdb',
        'URDF',
        'Kinect and Open Kinect',
        'OpenNI',
        'Arduino',
        'Postman',
        'TestRail',
        'JMeter',
        'JUnit',
        'Selenium',
        'QMetry',
        'Capybara',
        'Katalon Studio',
        'Cucumber',
        'LoadRunner',
        'GTMetrix',
        'TestNG',
        'TestStudio',
        'RSpec',
        'Clickup',
        'Appium',
        'SoapUI',
        'Go lang',
        'Lamp',
        'Amber JS',
        'TenserFlow',
        'TenserFlow Lite',
        'PyTorch',
        'Scikit-learn',
        'OpenCV',
        'Apache MXNet',
        'XGBoost',
        'Theano',
        'Open Neural Network Exchange',
        'Apache Hadoop',
        'Keras',
        'Matplotlib',
        'CUDA',
        'Pandas',
        'NLTK',
        'SpaCy',
        'Gensim',
        'Scrapy',
        'Beautiful Soup',
        'SQLAlchemy',
        'NetworkX',
        'Apache Spark',
        'Apache OpenNLP',
        'SymPy',
        'Tkinter',
        'Kivy',
        'PySide',
        'DEAP',
        'Visual Basic',
        'Requests',
        'Scapy',
        'Wireshark',
        'Tcpdump',
        'Nmap',
        'Ettercap',
        'Hping',
        'Metasploit Project',
        'Fiddler',
        'Strace',
        'Uncomplicated Firewall',
        'Telnet',
        'Nessus',
        'OpenSSL',
        'Capsa',
        'Kismet',
        'Deno',
        'Spring Boot',
        'Meteor',
        'Backbone.JS',
        'Nest.js',
        'R language',
        'Elasticsearch',
        'Kibana',
        'Redux',
        'NoSQL',
        'Preact',
        'Polymer',
        'Aurella',
        'Gatsby.JS',
        'Mithril.JS',
        'Nuxt.JS',
        'Stimulus.JS',
        'Jest.JS',
        'Tailwind CSS',
        'Playwright',
        'Swagger',
        'Maven',
        'Extent Reports',
        'Mocha',
        'Chai',
        'Watir',
        'Rest Assured',
        'Avo Assure',
        'TestComplete',
        'LambaTest',
        'BrowserTest',
        'Ruby on Rails, React',
        'Ruby on Rails, React Native',
        'Ruby on Rails',
        'React, Node',
        'Python',
        'PHP, Laravel',
        'Node',
        'Swift',
        'Ruby on Rails, Node',
        'Node, Python, Vue',
        'Cypress',
        'Ruby on Rails, Ionic',
        'React, React Native',
        'Node, React Native',
        'Java',
        'Angular, Node',
        'Vue',
        'Ruby, PHP',
        'Ruby on Rails, Ionic, React',
        'React JS, Django',
        'Python, React',
        'Python, PHP',
        'Python, AI/ML',
        'Java, Python, React',
        'Ionic, Angular JS',
        'Elixir',
        'DevOps',
        'Blockchain',
        'Angular',
        '.NET',
        'QA Manual',
        'QA Automation',
        'Metaverse',
        'Dynamics',
        'Pulumi',
        'Azure',
        'JVM',
        'MSLANG',
        'PLSQL'
      ].freeze
      # rubocop:enable Metrics/CollectionLiteralLength
    end
  end
end
